systemd-boot: Remove -mfpmath=sse option from cflags
EFI sources in systemd uses -mgeneral-regs-only which conflicts
with -mfpmath=sse specified by OE via tune arguments. It needs to
be removed, clang errors about it and fails the build

Fixes
error: the 'sse' unit is not supported with this instruction set

(From OE-Core rev: a7cbb7b90a9eb9f8a98054f8613a8230472cf4a5)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>